const translations = {
    vi: {
        "nav-home": "Trang Chủ",
        "nav-about": "Giới thiệu",
        "nav-solutions": "Giải pháp",
        "nav-projects": "Dự án",
        "nav-capabilities": "Năng lực",
        "nav-contact": "Liên hệ",

        "hero-title": "Giải Pháp Thiết Kế Xây Dựng <span>Hạng 1</span>",
        "hero-desc": "15 năm kinh nghiệm. Hơn 100 dự án lớn. Ứng dụng BIM chuyên sâu.",
        "hero-sub": "Đồng hành cùng Chủ đầu tư giải quyết bài toán phức tạp về Kiến trúc, Kết cấu, Cơ điện và Pháp lý.",
        "hero-btn-primary": "Khám phá giải pháp dành cho khách hàng",
        "hero-btn-secondary": "Xem Dự án",

        "stat-exp": "Năm kinh nghiệm",
        "stat-projects": "+ Dự án tiêu biểu",
        "stat-area": "Triệu m² sàn thiết kế",
        "stat-floors": "Tầng (Công trình cao nhất)",

        "about-title": "Giới Thiệu Về A.S.P.T",
        "about-subtitle": "Công ty TNHH MTV Tư vấn & Xây dựng A.S.P.T",
        
        "about-p1": "<strong>1. Trụ sở công ty:</strong> 82 & 84 đường Ngô Tất Tố, phường Hòa Cường, thành phố Đà Nẵng.<br><strong>Điện thoại giao dịch:</strong> (0236)-362.46.96 | <strong>Website:</strong> www.aspt.vn<br><strong>Chủ doanh nghiệp:</strong> Lê Viết Thành (CEO), mobile: 098.214.5011",
        "about-p2": "<strong>2. Ngày thành lập:</strong> 11/05/2011, theo giấy chứng nhận đăng ký kinh doanh số 0401423059 của Sở Kế hoạch Đầu tư Tp Đà Nẵng.",
        "about-p3": "<strong>3. Ngành nghề kinh doanh:</strong>",
        "about-l3-1": "Thiết kế Kiến trúc công trình Dân dụng & Công nghiệp.",
        "about-l3-2": "Thiết kế Kết cấu công trình Dân dụng & Công nghiệp.",
        "about-l3-3": "Thiết kế Cơ-Điện công trình Dân dụng & Công nghiệp.",
        "about-l3-4": "Lập quy hoạch 1/500 và hỗ trợ pháp lý trong quá trình thẩm định PCCC và xin cấp GPXD.",
        
        "about-p4": "<strong>4. Giới thiệu công ty:</strong>",
        "about-p4-desc1": "Công ty TNHH MTV Tư vấn và Xây dựng A.S.P.T chuyên thiết kế các công trình dân dụng, công nghiệp, đặc biệt là nhà cao tầng và các dự án có kết cấu phức tạp. Chúng tôi đã thực hiện nhiều công trình quy mô lớn, bao gồm các khách sạn tiêu chuẩn quốc tế, nhà máy và nhiều công trình đặc thù khác.",
        "about-p4-desc2": "Thế mạnh của công ty chúng tôi nổi bật ở các điểm sau: Đội ngũ chủ trì thiết kế đều có chứng chỉ hạng 1 và giàu kinh nghiệm, giúp phối hợp công việc hiệu quả. Toàn bộ quá trình thiết kế được thực hiện đồng bộ trên nền tảng BIM, đảm bảo sản phẩm chính xác và chất lượng. Chúng tôi có bề dày kinh nghiệm trong việc thiết kế các kết cấu phức tạp và hệ thống MEP, HVAC quy mô lớn. Sự am hiểu pháp luật và thực tiễn giúp công ty hỗ trợ pháp lý tối ưu cho các dự án. Ngoài ra, việc hợp tác với các đối tác kiến trúc uy tín tại Nhật Bản giúp chúng tôi cung cấp dịch vụ tổng thầu thiết kế chất lượng cao với chi phí hợp lý.",
        
        "about-p5": "<strong>Công ty A.S.P.T đã được cấp:</strong>",
        "about-l5-1": "Chứng chỉ Năng lực Hoạt động Xây dựng số 00000650 Hạng 1 ở nội dung thiết kế và thẩm tra công trình Dân dụng.",
        "about-l5-2": "Chứng chỉ Năng lực Hoạt động Xây dựng số DNA-00000650 Hạng 2 ở nội dung thiết kế và thẩm tra công trình Nhà Công nghiệp.",
        "about-l5-3": "Chứng chỉ Năng lực Hoạt động Xây dựng số HCM-00000650 Hạng 3 ở nội dung lập thiết kế quy hoạch xây dựng và thiết kế, thẩm tra công trình Hạ tầng kỹ thuật.",
        
        "about-p6": "<strong>5. Tiêu chí thiết kế:</strong> Tập trung nâng cao năng lực nhân sự và công cụ để cung cấp hồ sơ thiết kế chất lượng cao. Áp dụng giải pháp kỹ thuật tối ưu giúp chủ đầu tư tiết kiệm chi phí xây dựng, duy trì mức phí cạnh tranh, đảm bảo tiến độ nhanh và linh hoạt cập nhật thay đổi của dự án.",
        "about-p7": "<strong>6. Đối tượng khách hàng tiềm năng:</strong>",
        "about-l7-1": "Các chủ đầu tư dự án dân dụng quy mô từ trung bình tới lớn (đến cấp 1), bao gồm cả nội dung quy hoạch và thiết kế hạ tầng kỹ thuật.",
        "about-l7-2": "Các chủ đầu tư công trình căn hộ dòng tiền, biệt thự quy mô trung bình.",
        "about-l7-3": "Các chủ đầu tư các nhà máy, xí nghiệp, công trình công nghiệp quy mô từ nhỏ tới lớn (đến cấp 2), bao gồm cả nội dung quy hoạch và thiết kế hạ tầng kỹ thuật.",
        "about-l7-4": "Những đơn vị thiết kế chỉ chuyên sâu vào một lĩnh vực duy nhất đang có mong muốn liên kết thành lập liên danh nhằm cùng nhau đảm nhận thiết kế tổng thể dự án.",
        "about-l7-5": "Các đơn vị thi công đang tìm kiếm nhà thầu thiết kế để lập liên doanh D&B.",
        
        "about-p8": "<strong>7. Công trình tiêu biểu đã thiết kế:</strong> Với hơn 15 năm kinh nghiệm, chúng tôi đã thiết kế hơn 100 công trình có quy mô từ trung bình đến lớn, tiêu biểu như khách sạn Regis Bay, Brilliant, Vanda, Rosamia, Mường Thanh, TMS Luxury, tòa tháp PA Tower, vòng quay Sun Wheel, du thuyền Marina, Bệnh viện Gia đình, Đại học Đông Á, Tòa tháp văn phòng Danapha, nhà máy Danapha tại khu công nghệ cao, các dự án trường học FPT tại nhiều địa phương trên phạm vi cả nước,…",
        "about-p9": "<strong>8. Công cụ:</strong> Công ty đã đầu tư nhiều phần mềm bản quyền như: Etabs Ultimate v23, Adapt Builder 2020, Autodesk AEC (gồm Revit, Autocad, Naviswork, RSAP, Advance Steel, Civil 3D,…), Dbim & Dbim Steel, Ketcausoft, G8, CADEWA, ….",

        "sol-title": "Giải Pháp Dành Cho Khách Hàng",
        "sol-subtitle": "ASPT không chỉ cung cấp bản vẽ, chúng tôi mang đến giải pháp toàn diện, giải quyết mọi bài toán kỹ thuật và pháp lý.",
        
        "sol-1-t": "Chủ đầu tư Dự án Lớn (Cấp 1, Cấp 2)",
        "sol-1-d": "Tổng thầu thiết kế Kiến trúc, Kết cấu, MEP. Kinh nghiệm xử lý hầm sâu, nền đất yếu, cầu trục 100 tấn và thủ tục pháp lý phức tạp.",
        "sol-2-t": "Chủ đầu tư Dự án Vừa & Nhỏ",
        "sol-2-d": "Giải pháp tối ưu chi phí và không gian cho căn hộ cho thuê (6-9 tầng), khách sạn mini, biệt thự cao cấp.",
        "sol-3-t": "Đối Tác Thiết Kế (B2B)",
        "sol-3-d": "Hợp tác thiết kế chuyên sâu Kết cấu, Cơ điện, Lập dự toán, và triển khai mô hình BIM (LOD 300 - 400).",
        "sol-4-t": "Chủ đầu tư Dự án Quy hoạch & Hạ tầng kỹ thuật",
        "sol-4-d": "Lập quy hoạch chi tiết 1/500, thiết kế cơ sở hạ tầng kỹ thuật (cấp 3) nhanh chóng, chuẩn xác.",

        "proj-title": "Các Nhóm Dự Án Tiêu Biểu",
        "proj-subtitle": "Những công trình khẳng định năng lực Hạng 1 của ASPT trên khắp cả nước.",
        "proj-btn": "Xem tất cả dự án",

        "cap-title": "Năng Lực Cốt Lõi",
        "cap-subtitle": "Sở hữu đội ngũ chuyên gia và phần mềm bản quyền hàng đầu.",
        
        "cap-1-t": "Chứng chỉ Hạng 1",
        "cap-1-d": "BXD-00000650: Thiết kế & Thẩm tra Dân dụng Hạng 1. Đội ngũ chủ trì cơ hữu giàu kinh nghiệm.",
        "cap-2-t": "Công nghệ BIM",
        "cap-2-d": "Ứng dụng triệt để BIM trong thiết kế giúp phát hiện xung đột sớm, tối ưu khối lượng và chi phí thi công.",
        "cap-3-t": "Pháp lý Vững vàng",
        "cap-3-d": "Đồng hành xử lý các thủ tục cấp phép, thẩm định PCCC nhanh chóng theo quy định mới nhất.",

        "footer-about": "Công ty TNHH MTV Tư vấn & Xây dựng A.S.P.T - Giải pháp thiết kế xây dựng Hạng 1 toàn diện cho mọi công trình.",
        "footer-contact-title": "Liên hệ",
        "footer-contact-address": "82 & 84 Ngô Tất Tố, phường Hòa Cường, Thành phố Đà Nẵng, Việt Nam",
        "footer-connect": "Kết nối",
        
        "about-btn-more": "Xem thêm thông tin về chúng tôi",
        "about-toggle-expand": "Hiện thêm",
        "about-toggle-collapse": "Thu gọn bớt",
        "sol-btn-ai": "Trao đổi với AI-Agent của chúng tôi về dự án của bạn",
        "footer-recruitment-btn": "Liên hệ tuyển dụng",
        "modal-about-title": "Về Chúng Tôi - A.S.P.T",
        "modal-about-tab-legal": "Hồ sơ pháp lý",
        "modal-about-tab-activities": "Hoạt động & Văn hóa",
        "btn-back": "Quay lại danh sách",
        "btn-back-simple": "Quay lại",
        "modal-legal-p1": "Dưới đây là các văn bản pháp lý khẳng định năng lực Hạng 1 của chúng tôi do Bộ Xây dựng cấp phép:",
        "modal-legal-doc1-title": "Chứng chỉ Năng lực Hạng 1",
        "modal-legal-doc1-desc": "Số BXD-00000650 do Bộ Xây dựng cấp về thiết kế & thẩm tra Dân dụng.",
        "modal-legal-doc2-title": "Chứng nhận ISO 9001:2015",
        "modal-legal-doc2-desc": "Hệ thống quản lý chất lượng thiết kế xây dựng đạt tiêu chuẩn quốc tế.",
        "modal-btn-view": "Xem bản Scan",
        "modal-act-p1": "Một số hình ảnh và video về văn hóa doanh nghiệp và hoạt động nội bộ của A.S.P.T:",
        "modal-gallery-temp": "Album ảnh đang được tải...",
        "modal-sol-list-title": "Danh sách bài viết",
        "modal-rec-title": "Cơ Hội Nghề Nghiệp Tại A.S.P.T",
        "modal-rec-p1": "Tại A.S.P.T, chúng tôi luôn tìm kiếm những nhân tài đam mê thiết kế kiến trúc, quy hoạch, kỹ thuật kết cấu, cơ điện (MEP), dự toán và ứng dụng công nghệ BIM. Hãy đồng hành cùng chúng tôi để kiến tạo các công trình Hạng 1 tầm cỡ quốc gia.",
        "modal-job1-title": "Kỹ sư Thiết kế Kết cấu (Dân dụng & Công nghiệp)",
        "modal-job1-req": "Yêu cầu: Tốt nghiệp ĐH chuyên ngành Xây dựng, sử dụng thành thạo Etabs, SAFE, Revit Structure. Có tối thiểu 3 năm kinh nghiệm.",
        "modal-job2-title": "Kỹ sư Cơ Điện (MEP Coordinator)",
        "modal-job2-req": "Yêu cầu: Thiết kế hệ thống điện, HVAC hoặc cấp thoát nước, có kinh nghiệm triển khai mô hình BIM Revit MEP.",
        "job-type-full": "Toàn thời gian",
        "modal-rec-apply-title": "Cách thức ứng tuyển",
        "modal-rec-apply-p": "Ứng viên vui lòng gửi CV và Hồ sơ năng lực (Portfolio dự án) về địa chỉ email:",
        "modal-rec-apply-note": "Tiêu đề email ghi rõ: [Ứng tuyển] - Vị trí - Họ tên - Số điện thoại",
        "chat-status-online": "Trực tuyến 24/7",
        "chat-bot-welcome": "Kính chào quý khách! Tôi là Trợ lý trí tuệ nhân tạo đến từ ASPT. Tôi luôn sẵn sàng cung cấp hướng dẫn chi tiết liên quan tới việc lập quy hoạch, tư vấn pháp lý, lập hồ sơ thiết kế phần kiến trúc, kết cấu, cơ điện, hạ tầng kỹ thuật, dự toán… cho các dự án dân dụng và công nghiệp. Tôi cũng có thể giúp bạn sắp xếp một cuộc trao đổi trực tiếp cùng ban lãnh đạo của chúng tôi. Xin cho biết bạn đang cần hỗ trợ về lĩnh vực nào?",
        "chat-placeholder": "Nhập câu hỏi của bạn..."
    },
    en: {
        "nav-home": "Home",
        "nav-about": "About Us",
        "nav-solutions": "Solutions",
        "nav-projects": "Projects",
        "nav-capabilities": "Capabilities",
        "nav-contact": "Contact",

        "hero-title": "Class 1 Construction Design Solutions",
        "hero-desc": "15 years of experience. Over 100 major projects. In-depth BIM application.",
        "hero-sub": "Partnering with Investors to solve complex Architectural, Structural, MEP, and Legal challenges.",
        "hero-btn-primary": "Explore Client Solutions",
        "hero-btn-secondary": "View Projects",

        "stat-exp": "Years of Experience",
        "stat-projects": "+ Outstanding Projects",
        "stat-area": "Million m² Designed",
        "stat-floors": "Floors (Tallest Building)",

        "about-title": "About A.S.P.T",
        "about-subtitle": "A.S.P.T Consulting & Construction Co., Ltd",
        
        "about-p1": "<strong>1. Headquarters:</strong> 82 & 84 Ngo Tat To Street, Hoa Cuong Ward, Da Nang City.<br><strong>Phone:</strong> (0236)-362.46.96 | <strong>Website:</strong> www.aspt.vn<br><strong>CEO:</strong> Le Viet Thanh, mobile: 098.214.5011",
        "about-p2": "<strong>2. Established:</strong> May 11, 2011, under Business Registration Certificate No. 0401423059 by Da Nang Department of Planning and Investment.",
        "about-p3": "<strong>3. Business Sectors:</strong>",
        "about-l3-1": "Architectural Design of Civil & Industrial Works.",
        "about-l3-2": "Structural Design of Civil & Industrial Works.",
        "about-l3-3": "MEP Design of Civil & Industrial Works.",
        "about-l3-4": "1/500 Master Planning and legal support during Fire Safety appraisal and Construction Permitting.",
        
        "about-p4": "<strong>4. Company Introduction:</strong>",
        "about-p4-desc1": "A.S.P.T Consulting & Construction Co., Ltd specializes in designing civil and industrial projects, especially high-rise buildings and complex structures. We have executed many large-scale projects, including international standard hotels, factories, and highly specialized facilities.",
        "about-p4-desc2": "Our strengths include a highly experienced team of lead designers with Class 1 certification. The entire design process is synchronized on the BIM platform, ensuring accuracy and high quality. We possess extensive experience in complex structural design and large-scale MEP/HVAC systems. Our deep understanding of practical law allows us to provide optimal legal support. Furthermore, partnerships with reputable architectural firms in Japan enable us to deliver high-quality design general contracting services at reasonable costs.",
        
        "about-p5": "<strong>A.S.P.T holds the following Certificates:</strong>",
        "about-l5-1": "Construction Operation Capability Certificate No. 00000650 - Class 1 in Civil Engineering Design and Verification.",
        "about-l5-2": "Construction Operation Capability Certificate No. DNA-00000650 - Class 2 in Industrial Engineering Design and Verification.",
        "about-l5-3": "Construction Operation Capability Certificate No. HCM-00000650 - Class 3 in Urban Planning and Infrastructure Engineering Design and Verification.",
        
        "about-p6": "<strong>5. Design Criteria:</strong> Focus on enhancing personnel capacity and tools to provide high-quality design documents. Apply optimal technical solutions to help investors save construction costs, maintain competitive fees, ensure rapid progress, and flexibly adapt to project changes.",
        "about-p7": "<strong>6. Target Clients:</strong>",
        "about-l7-1": "Investors of medium to large civil projects (up to Class 1), including urban planning and infrastructure design.",
        "about-l7-2": "Investors of cash-flow apartments and medium-scale villas.",
        "about-l7-3": "Investors of factories, enterprises, and industrial works from small to large scales (up to Class 2).",
        "about-l7-4": "Specialized design units looking to form a consortium to undertake overall project design.",
        "about-l7-5": "Construction contractors seeking design partners to form Design & Build (D&B) ventures.",
        
        "about-p8": "<strong>7. Notable Projects:</strong> With over 15 years of experience, we have designed over 100 medium to large projects, such as Regis Bay, Brilliant, Vanda, Rosamia, and Muong Thanh Hotels, TMS Luxury, PA Tower, Sun Wheel, Marina Yacht, Family Hospital, Dong A University, Danapha Office Tower, Danapha High-Tech Factory, and FPT School projects nationwide.",
        "about-p9": "<strong>8. Tools:</strong> We invest in licensed software such as: Etabs Ultimate v23, Adapt Builder 2020, Autodesk AEC (Revit, Autocad, Naviswork, RSAP, Advance Steel, Civil 3D), Dbim & Dbim Steel, Ketcausoft, G8, CADEWA, etc.",

        "sol-title": "Client Solutions",
        "sol-subtitle": "ASPT provides comprehensive solutions, solving all technical and legal problems.",
        
        "sol-1-t": "Large Investors (Class 1, 2)",
        "sol-1-d": "General Design Contractor (Architecture, Structure, MEP). Experienced in deep basements, weak soil, 100-ton cranes, and legal procedures.",
        "sol-2-t": "Medium & Small Projects",
        "sol-2-d": "Cost and space optimization for rental apartments (6-9 floors), mini-hotels, and luxury villas.",
        "sol-3-t": "Design Partners (B2B)",
        "sol-3-d": "Deep cooperation in Structure, MEP, Estimating, and BIM modeling (LOD 300 - 400).",
        "sol-4-t": "Planning & Infrastructure",
        "sol-4-d": "1/500 detailed planning and Level 3 infrastructure design delivered quickly and accurately.",

        "proj-title": "Outstanding Project Groups",
        "proj-subtitle": "Projects affirming ASPT's Class 1 capabilities nationwide.",
        "proj-btn": "View all projects",

        "cap-title": "Core Capabilities",
        "cap-subtitle": "Owning a team of top experts and licensed software.",
        
        "cap-1-t": "Class 1 Certificate",
        "cap-1-d": "BXD-00000650: Class 1 Civil Design & Verification. Experienced in-house lead team.",
        "cap-2-t": "BIM Technology",
        "cap-2-d": "Thorough application of BIM helps detect clashes early, optimizing volume and construction costs.",
        "cap-3-t": "Strong Legal Foundation",
        "cap-3-d": "Accompanying the handling of fast licensing and Fire Safety appraisal procedures.",

        "footer-about": "A.S.P.T Consulting & Construction Co., Ltd - Comprehensive Class 1 construction design solutions.",
        "footer-contact-title": "Contact",
        "footer-contact-address": "82 & 84 Ngo Tat To St., Hoa Cuong Ward, Da Nang City, Vietnam",
        "footer-connect": "Connect",
        
        "about-btn-more": "Learn more about us",
        "about-toggle-expand": "Show more",
        "about-toggle-collapse": "Collapse",
        "sol-btn-ai": "Chat with our AI Agent about your project",
        "footer-recruitment-btn": "Careers / Recruitment",
        "modal-about-title": "About Us - A.S.P.T",
        "modal-about-tab-legal": "Legal Profile",
        "modal-about-tab-activities": "Activities & Culture",
        "btn-back": "Back to list",
        "btn-back-simple": "Back",
        "modal-legal-p1": "Here are the legal documents confirming our Class 1 capacity licensed by the Ministry of Construction:",
        "modal-legal-doc1-title": "Class 1 Design Certificate",
        "modal-legal-doc1-desc": "No. BXD-00000650 issued by the Ministry of Construction for civil design & appraisal.",
        "modal-legal-doc2-title": "ISO 9001:2015 Certification",
        "modal-legal-doc2-desc": "Quality management system for construction design complies with international standards.",
        "modal-btn-view": "View Scan",
        "modal-act-p1": "Some photos and videos of corporate culture and internal activities of A.S.P.T:",
        "modal-gallery-temp": "Photo album loading...",
        "modal-sol-list-title": "Article Playlist",
        "modal-rec-title": "Career Opportunities at A.S.P.T",
        "modal-rec-p1": "At A.S.P.T, we are always looking for talents passionate about architectural design, planning, structural engineering, MEP, estimating, and BIM. Join us to create state-of-the-art national Class 1 projects.",
        "modal-job1-title": "Structural Design Engineer (Civil & Industrial)",
        "modal-job1-req": "Requirements: University Degree in Civil Engineering, proficient in Etabs, SAFE, Revit Structure. Min 3 years experience.",
        "modal-job2-title": "MEP Engineer (MEP Coordinator)",
        "modal-job2-req": "Requirements: Design electrical, HVAC, or plumbing systems, experience with Revit MEP modeling.",
        "job-type-full": "Full-time",
        "modal-rec-apply-title": "How to Apply",
        "modal-rec-apply-p": "Candidates please send your CV and project portfolio to email:",
        "modal-rec-apply-note": "Email subject: [Apply] - Position - Full Name - Phone Number",
        "chat-status-online": "Online 24/7",
        "chat-bot-welcome": "Dear Valued Customer! I am the Artificial Intelligence Assistant from ASPT. I am always ready to provide detailed guidance related to planning, legal consulting, design document preparation for architecture, structure, M&E, infrastructure, cost estimation... for civil and industrial projects. I can also help you arrange a direct discussion with our management team. Please let us know which area you need assistance with?",
        "chat-placeholder": "Type your question..."
    },
    ja: {
        "nav-home": "ホーム",
        "nav-about": "私たちについて",
        "nav-solutions": "ソリューション",
        "nav-projects": "プロジェクト",
        "nav-capabilities": "能力",
        "nav-contact": "連絡",

        "hero-title": "クラス1 建築設計ソリューション",
        "hero-desc": "15年の経験。100以上の大規模プロジェクト。BIMの深い活用。",
        "hero-sub": "建築、構造、MEP、法的課題の解決において投資家をサポートします。",
        "hero-btn-primary": "クライアント向けソリューションを見る",
        "hero-btn-secondary": "プロジェクトを見る",

        "stat-exp": "年の経験",
        "stat-projects": "+ 注目プロジェクト",
        "stat-area": "百万m²の設計面積",
        "stat-floors": "階建て (最高層建築)",

        "about-title": "A.S.P.T について",
        "about-subtitle": "A.S.P.T コンサルティング＆建設株式会社",
        
        "about-p1": "<strong>1. 本社:</strong> ダナン市ホアクオン区ゴータットトー通り82・84番地<br><strong>電話:</strong> (0236)-362.46.96 | <strong>ウェブサイト:</strong> www.aspt.vn<br><strong>CEO:</strong> レ・ビエット・タン, mobile: 098.214.5011",
        "about-p2": "<strong>2. 設立:</strong> 2011年5月11日 (事業登録証明書番号0401423059、ダナン市計画投資局発行)",
        "about-p3": "<strong>3. 事業内容:</strong>",
        "about-l3-1": "民生用および産業用建築物の意匠設計。",
        "about-l3-2": "民生用および産業用建築物の構造設計。",
        "about-l3-3": "民生用および産業用建築物のMEP設計。",
        "about-l3-4": "1/500の基本計画、消防評価および建築許可申請中の法的サポート。",
        
        "about-p4": "<strong>4. 会社紹介:</strong>",
        "about-p4-desc1": "A.S.P.Tコンサルティング＆建設株式会社は、土木および産業プロジェクト、特に高層ビルや複雑な構造物の設計を専門としています。国際基準のホテルや工場など、数多くの大規模プロジェクトを実施してきました。",
        "about-p4-desc2": "当社の強みは、クラス1認定を受けた経験豊富な設計チームにあります。設計プロセス全体がBIMプラットフォーム上で同期され、精度と品質を保証します。大規模なMEP/HVACシステムや複雑な構造設計において豊富な経験を有しています。実務的な法律知識により、プロジェクトに最適な法的サポートを提供します。さらに、日本の著名な建築事務所との提携により、高品質な設計総合請負サービスを合理的なコストで提供します。",
        
        "about-p5": "<strong>A.S.P.T 取得済み証明書:</strong>",
        "about-l5-1": "建設事業能力証明書 第00000650号 - 土木設計・検証 クラス1",
        "about-l5-2": "建設事業能力証明書 第DNA-00000650号 - 産業施設設計・検証 クラス2",
        "about-l5-3": "建設事業能力証明書 第HCM-00000650号 - 都市計画およびインフラ設計・検証 クラス3",
        
        "about-p6": "<strong>5. 設計基準:</strong> 高品質な設計図書を提供するため、人材能力とツールの向上に注力します。最適な技術ソリューションを適用し、建設コストの削減、競争力のある料金の維持、スケジュールの確保、プロジェクト変更への柔軟な対応を実現します。",
        "about-p7": "<strong>6. 対象クライアント:</strong>",
        "about-l7-1": "中～大規模（クラス1まで）の土木プロジェクト（都市計画およびインフラ設計を含む）の投資家。",
        "about-l7-2": "収益型アパートや中規模ヴィラの投資家。",
        "about-l7-3": "小～大規模（クラス2まで）の工場・産業施設の投資家。",
        "about-l7-4": "コンソーシアムを結成してプロジェクト全体の設計を引き受けたい専門設計機関。",
        "about-l7-5": "設計施工（D&B）事業を形成するための設計パートナーを探している建設業者。",
        
        "about-p8": "<strong>7. 主な実績:</strong> 15年以上の経験を持ち、Regis Bay、Brilliant、Vanda、Rosamia、Muong Thanhなどのホテル、TMS Luxury、PA Tower、Sun Wheel、Marina Yacht、Family Hospital、Dong A大学、Danaphaオフィスタワー、FPT学校プロジェクトなど、100を超える中～大規模プロジェクトを設計してきました。",
        "about-p9": "<strong>8. ツール:</strong> Etabs Ultimate v23、Adapt Builder 2020、Autodesk AEC（Revit、Autocad、Naviswork、RSAP、Advance Steel、Civil 3D）、Dbim＆Dbim Steel、Ketcausoft、G8、CADEWAなどのライセンスソフトウェアに投資しています。",

        "sol-title": "クライアント向けソリューション",
        "sol-subtitle": "ASPTは図面を提供するだけでなく、技術的および法的な問題を解決する包括的なソリューションを提供します。",
        
        "sol-1-t": "大規模投資家 (クラス1, 2)",
        "sol-1-d": "意匠・構造・MEPの設計総合請負。深い地下室、軟弱地盤、100トンクレーン、複雑な法的手続きの経験。",
        "sol-2-t": "中・小規模プロジェクト",
        "sol-2-d": "賃貸アパート（6〜9階）、ミニホテル、高級ヴィラのコストとスペースの最適化。",
        "sol-3-t": "設計パートナー (B2B)",
        "sol-3-d": "構造、MEP、積算、BIMモデリング（LOD 300 - 400）における深い協力。",
        "sol-4-t": "都市計画・インフラ",
        "sol-4-d": "1/500の詳細な計画とインフラストラクチャの設計を迅速かつ正確に。",

        "proj-title": "優秀なプロジェクトグループ",
        "proj-subtitle": "全国でASPTのクラス1の能力を証明するプロジェクト。",
        "proj-btn": "すべてのプロジェクトを見る",

        "cap-title": "コアコンピタンス",
        "cap-subtitle": "トップクラスの専門家チームとライセンスソフトウェアを所有しています。",
        
        "cap-1-t": "クラス1 証明書",
        "cap-1-d": "BXD-00000650: 土木設計および検証クラス1。経験豊富な社内チーム。",
        "cap-2-t": "BIMテクノロジー",
        "cap-2-d": "BIMの徹底的な適用により、衝突を早期に発見し、建設コストを最適化します。",
        "cap-3-t": "強固な法的基盤",
        "cap-3-d": "迅速なライセンス供与と消防評価手続きの処理をサポートします。",

        "footer-about": "A.S.P.T コンサルティング＆建設株式会社 - 包括的なクラス1建築設計ソリューション。",
        "footer-contact-title": "お問い合わせ",
        "footer-contact-address": "ベトナム ダナン市 ホアクオン区 ゴータットトー通り 82 & 84",
        "footer-connect": "接続",
        
        "about-btn-more": "詳細を見る",
        "about-toggle-expand": "もっと見る",
        "about-toggle-collapse": "折りたたむ",
        "sol-btn-ai": "プロジェクトについてAIエージェントに相談する",
        "footer-recruitment-btn": "採用情報 / キャリア",
        "modal-about-title": "会社概要 - A.S.P.T",
        "modal-about-tab-legal": "法適合証明書",
        "modal-about-tab-activities": "活動と企業文化",
        "btn-back": "リストに戻る",
        "btn-back-simple": "戻る",
        "modal-legal-p1": "以下は、建設省によって認可されたクラス1の設計能力を証明する法的文書です。",
        "modal-legal-doc1-title": "クラス1建築設計資格",
        "modal-legal-doc1-desc": "民間設計・審査のために建設省から発行された第BXD-00000650号。",
        "modal-legal-doc2-title": "ISO 9001:2015 認証",
        "modal-legal-doc2-desc": "建築設計品質管理システムは国際規格に準拠しています。",
        "modal-btn-view": "スキャンを見る",
        "modal-act-p1": "企業文化およびA.S.P.Tの社内活動の写真とビデオ：",
        "modal-gallery-temp": "写真アルバム読み込み中...",
        "modal-sol-list-title": "記事プレイリスト",
        "modal-rec-title": "A.S.P.T でのキャリア機会",
        "modal-rec-p1": "A.S.P.Tでは、建築設計、都市計画、構造工学、MEP、積算、BIMテクノロジーに情熱を持つ優秀な人材を常に募集しています。一流の国家規模プロジェクトを共に設計しましょう。",
        "modal-job1-title": "構造設計エンジニア（民間＆産業用）",
        "modal-job1-req": "要件：土木工学の大学学位。Etabs、SAFE、Revit Structureに精通。3年以上の実務経験。",
        "modal-job2-title": "設備エンジニア（MEPコーディネーター）",
        "modal-job2-req": "要件：電気、空調、給排水システムの設計。Revit MEPモデリングの経験。",
        "job-type-full": "正社員",
        "modal-rec-apply-title": "応募方法",
        "modal-rec-apply-p": "履歴書とプロジェクトポートフォリオをメールでお送りください。",
        "modal-rec-apply-note": "メール件名: [応募] - 職種 - 氏名 - 電話番号",
        "chat-status-online": "24時間対応",
        "chat-bot-welcome": "お客様、ようこそ！私はASPTの人工知能アシスタントです。民生用および産業用プロジェクトの計画立案、法的コンサルティング、意匠、構造、設備、インフラ設計、見積もりに関する詳細なご案内をいつでも提供いたします。また、当社の経営陣との直接の打ち合わせを手配することもできます。どの分野でのサポートをご希望ですか？",
        "chat-placeholder": "質問を入力してください..."
    },
    zh: {
        "nav-home": "首页",
        "nav-about": "关于我们",
        "nav-solutions": "解决方案",
        "nav-projects": "项目",
        "nav-capabilities": "核心能力",
        "nav-contact": "联系",

        "hero-title": "一级建筑设计解决方案",
        "hero-desc": "15年经验。超过100个大型项目。深度BIM应用。",
        "hero-sub": "与投资者携手解决建筑、结构、机电及法律方面的复杂难题。",
        "hero-btn-primary": "探索客户解决方案",
        "hero-btn-secondary": "查看项目",

        "stat-exp": "年经验",
        "stat-projects": "+ 典型项目",
        "stat-area": "百万平方米设计面积",
        "stat-floors": "层 (最高建筑)",

        "about-title": "关于 A.S.P.T",
        "about-subtitle": "A.S.P.T 咨询与建设单成员有限责任公司",
        
        "about-p1": "<strong>1. 公司总部:</strong> 岘港市海洲郡和强坊吴达素街82和84号。<br><strong>交易电话:</strong> (0236)-362.46.96 | <strong>网站:</strong> www.aspt.vn<br><strong>企业主:</strong> 黎曰成 (CEO), mobile: 098.214.5011",
        "about-p2": "<strong>2. 成立日期:</strong> 2011年5月11日，根据岘港市计划投资局颁发的第0401423059号营业执照成立。",
        "about-p3": "<strong>3. 经营范围:</strong>",
        "about-l3-1": "民用及工业工程建筑设计。",
        "about-l3-2": "民用及工业工程结构设计。",
        "about-l3-3": "民用及工业工程机电(MEP)设计。",
        "about-l3-4": "1/500规划编制以及消防审批和申请施工许可证过程中的法律支持。",
        
        "about-p4": "<strong>4. 公司简介:</strong>",
        "about-p4-desc1": "A.S.P.T 咨询与建设有限公司专业从事民用和工业项目的设计，特别是高层建筑和复杂结构项目。我们已实施许多大型项目，包括国际标准酒店、工厂及许多特殊工程。",
        "about-p4-desc2": "我们公司的优势突出表现在以下几点：主案设计团队均拥有一级证书且经验丰富，有助于高效协调工作。整个设计过程在BIM平台上同步进行，确保产品精准和高质量。我们在复杂结构设计和大型MEP、HVAC系统方面拥有丰富的经验。对法律和实践的深刻理解使公司能够为项目提供最佳的法律支持。此外，与日本知名建筑合作伙伴的合作帮助我们以合理的成本提供高质量的设计总包服务。",
        
        "about-p5": "<strong>A.S.P.T 公司已获得:</strong>",
        "about-l5-1": "建设活动能力证书编号 00000650 一级 - 民用工程设计与审查内容。",
        "about-l5-2": "建设活动能力证书编号 DNA-00000650 二级 - 工业建筑设计与审查内容。",
        "about-l5-3": "建设活动能力证书编号 HCM-00000650 三级 - 建筑规划设计编制及基础设施工程设计、审查内容。",
        
        "about-p6": "<strong>5. 设计标准:</strong> 专注于提升人员能力和工具，以提供高质量的设计文件。应用最优技术解决方案，帮助投资者节省建设成本，保持具有竞争力的费用，确保进度快速并灵活适应项目变更。",
        "about-p7": "<strong>6. 潜在客户对象:</strong>",
        "about-l7-1": "中大型民用项目（至一级）的投资者，包括规划和基础设施设计内容。",
        "about-l7-2": "现金流公寓、中等规模别墅工程的投资者。",
        "about-l7-3": "中小型至大型工厂、企业、工业工程（至二级）的投资者，包括规划和基础设施设计内容。",
        "about-l7-4": "只专注于单一领域的专业设计单位，希望结盟组建联合体以共同承担项目总体设计。",
        "about-l7-5": "正在寻找设计承包商以成立D&B联合体的施工单位。",
        
        "about-p8": "<strong>7. 典型设计工程:</strong> 凭借超过15年的经验，我们设计了100多项中大型工程，典型项目如：Regis Bay、Brilliant、Vanda、Rosamia、孟青(Muong Thanh)酒店，TMS Luxury，PA Tower大厦，太阳摩天轮(Sun Wheel)，Marina游艇，家庭医院，东亚大学，Danapha办公大楼，高新区的Danapha工厂，全国多地的FPT学校项目等...",
        "about-p9": "<strong>8. 工具:</strong> 公司投资了许多正版软件，如：Etabs Ultimate v23, Adapt Builder 2020, Autodesk AEC (包括Revit, Autocad, Naviswork, RSAP, Advance Steel, Civil 3D等), Dbim & Dbim Steel, Ketcausoft, G8, CADEWA等。",

        "sol-title": "为客户提供的解决方案",
        "sol-subtitle": "ASPT不仅提供图纸，我们提供全面的解决方案，解决所有技术和法律难题。",
        
        "sol-1-t": "大型项目投资者 (一级, 二级)",
        "sol-1-d": "建筑、结构、机电设计总包。拥有处理深基坑、软土地基、100吨桥式起重机和复杂法律程序的经验。",
        "sol-2-t": "中小型项目",
        "sol-2-d": "为出租公寓 (6-9层)、迷你酒店、高级别墅优化成本和空间的解决方案。",
        "sol-3-t": "设计合作伙伴 (B2B)",
        "sol-3-d": "深入合作进行结构、机电设计、预算编制及部署BIM模型 (LOD 300 - 400)。",
        "sol-4-t": "规划与基础设施",
        "sol-4-d": "快速准确地编制1/500详细规划、设计技术基础设施 (三级)。",

        "proj-title": "优秀项目组",
        "proj-subtitle": "彰显ASPT全国一级能力的工程。",
        "proj-btn": "查看所有项目",

        "cap-title": "核心能力",
        "cap-subtitle": "拥有一流的专家团队和正版软件。",
        
        "cap-1-t": "一级证书",
        "cap-1-d": "BXD-00000650: 一级民用设计与审查。经验丰富的内部骨干团队。",
        "cap-2-t": "BIM 技术",
        "cap-2-d": "在设计中彻底应用BIM，帮助尽早发现冲突，优化工程量和施工成本。",
        "cap-3-t": "坚实的法律基础",
        "cap-3-d": "伴随并根据最新规定快速处理审批和消防审批手续。",

        "footer-about": "A.S.P.T 咨询与建设单成员有限责任公司 - 适用于所有工程的全面一级建筑设计解决方案。",
        "footer-contact-title": "联系",
        "footer-contact-address": "越南，岘港市，和强坊，吴达素街82和84号",
        "footer-connect": "联系我们",
        
        "about-btn-more": "了解更多关于我们",
        "about-toggle-expand": "显示更多",
        "about-toggle-collapse": "收起",
        "sol-btn-ai": "与我们的AI助手探讨您的项目",
        "footer-recruitment-btn": "招聘信息 / 职业生涯",
        "modal-about-title": "关于我们 - A.S.P.T",
        "modal-about-tab-legal": "活动与文化",
        "modal-about-tab-activities": "活动与文化",
        "btn-back": "返回列表",
        "btn-back-simple": "返回",
        "modal-legal-p1": "以下是建设部颁发的一级设计资质证明及相关法律文件：",
        "modal-legal-doc1-title": "一级设计能力证书",
        "modal-legal-doc1-desc": "建设部颁发的第BXD-00000650号民用设计与审查证书。",
        "modal-legal-doc2-title": "ISO 9001:2015 质量管理认证",
        "modal-legal-doc2-desc": "建筑设计质量管理体系符合国际标准。",
        "modal-btn-view": "查看扫描件",
        "modal-act-p1": "A.S.P.T的团队文化和内部活动的部分图片与视频：",
        "modal-gallery-temp": "相册加载中...",
        "modal-sol-list-title": "文章列表",
        "modal-rec-title": "A.S.P.T 职业机会",
        "modal-rec-p1": "在A.S.P.T，我们一直在寻找对建筑设计、规划、结构工程、机电(MEP)、预算编制和BIM技术充满热情的杰出人才。加入我们，共同设计国家级的一级大型项目。",
        "modal-job1-title": "结构设计工程师（民用与工业）",
        "modal-job1-req": "要求：土木工程专业大学本科，熟练使用Etabs、SAFE、Revit Structure。至少3年相关经验。",
        "modal-job2-title": "机电工程师（MEP协调员）",
        "modal-job2-req": "要求：设计电气、暖通或给排水系统，具备Revit MEP建模经验。",
        "job-type-full": "全职",
        "modal-rec-apply-title": "如何申请",
        "modal-rec-apply-p": "请将您的简历及项目作品集发送至以下邮箱：",
        "modal-rec-apply-note": "邮件主题: [应聘] - 职位 - 姓名 - 电话号码",
        "chat-status-online": "24/7在线",
        "chat-bot-welcome": "尊敬的顾客，您好！我是来自ASPT的人工智能助手。我随时准备为您提供民用与工业项目的规划编制、法律咨询、建筑、结构、机电、市政工程设计文件编制、预算等方面的详细指导。我还可以帮您安排与我们管理团队的直接交流。请问您需要哪个领域的支持？",
        "chat-placeholder": "请输入您的问题..."
    }
};
